#!/bin/sh
':' //; exec "$(command -v nodejs || command -v node)" "$0" "$@"

var fs = require('fs');

var MINIFY_FILE = 'layout.jade';
var COMMENT_SCRIPT = 'script(src="javascripts/Selector.js")';

fs.readFile(MINIFY_FILE, function(err, data) {
	if (err) throw err;
	var data = data + '';

	// Find text between 2 strings
	var toReplace = data.split('\/\/-MINIFYSTART').pop().split('\/\/-MINIFYEND')[0];

	fs.readFile('../public/javascripts/Selector.min.js', function(err, selector) {
		if (err) throw err;

		// Inefficient, but obvious
		var replacer = '\n        script\n            ' + selector + '\n\        ';
		var newData = data.replace(toReplace, replacer);
		if (newData.indexOf('\/\/-' + COMMENT_SCRIPT) < 0){
			var newData = data.replace(COMMENT_SCRIPT, '\/\/-' + COMMENT_SCRIPT);
		}

		fs.writeFile(MINIFY_FILE, newData, function() {
			if (err) throw err;

			console.log(MINIFY_FILE, 'minified')
		});
	});
});